name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: mingw-w64-i686-toolchain mingw-w64-i686-SDL2 mingw-w64-i686-SDL2_image mingw-w64-i686-stb mingw-w64-i686-ntldd
        release: false
    
    - name: Compile
      run: mingw32-make all
    
    - name: Add DLLs
      run: |
        cd bin/release
        ntldd u8-emu-frontend-cpp.exe | grep "msys" | awk '{print $3}' | sed 's/\\/\//g' > dlls.txt
        xargs -a dlls.txt cp -t .
        7z a u8-emu-frontend-cpp.zip u8-emu-frontend-cpp.exe *.dll
    
    - name: Upload to Releases page
      uses: softprops/action-gh-release@v2
      with:
        body: "NOTE: This is a continuous release. Binaries are rebuilt automatically when changes are made."
        name: Continuous build
        tag_name: continuous
        files: u8-emu-frontend-cpp.zip
