name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.MY_TOKEN }}
        submodules: recursive
    
    - name: Setup MSYS2 MINGW64
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-sdl3 mingw-w64-x86_64-sdl3-image mingw-w64-x86_64-stb mingw-w64-x86_64-ntldd mingw-w64-x86_64-libzip
        release: false
    
    - name: Compile
      run: mingw32-make CXXFLAGS_EX="-DGITHUB_RUNID=${{ github.run_id }}" all
    
    - name: Create ZIP package
      run: |
        cd bin/release
        ntldd -R u8-emu-frontend-cpp.exe | grep "msys" | awk '{print $3}' | sed 's/\\/\//g' > dlls.txt
        xargs -a dlls.txt cp -t .
        ziptool -n u8-emu-frontend-cpp-win64.zip add_file LICENSE ../../LICENSE add_dir u8-emu-frontend-cpp add_file u8-emu-frontend-cpp/u8-emu-frontend-cpp.exe u8-emu-frontend-cpp.exe 0 $(stat -c%s "u8-emu-frontend-cpp.exe")
        for dll in *.dll; do [ -f "$dll" ] && ziptool u8-emu-frontend-cpp-win64.zip add_file "u8-emu-frontend-cpp/$dll" "$dll" 0 $(stat -c%s "$dll"); done
    
    - name: Delete old release
      uses: larryjoelane/delete-release-action@v1.0.24
      with:
        release-name: continuous
        token: ${{ secrets.MY_TOKEN }}

    - name: Create new release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.MY_TOKEN }}
        body: "NOTE: This is a continuous release. Binaries are rebuilt automatically when changes are made."
        name: Continuous build
        tag_name: continuous
        files: bin/release/u8-emu-frontend-cpp-win64.zip
        draft: false
        make_latest: true
